### ISSUE TITLE
KeyError: 'status'

### ISSUE THREAD

**Issue by bcoles** [manu-chroma/username-availability-checker#106]
Ran into this issue, with a few different usernames, on different sites.

```
$ python3 cli.py 
Enter the username : asdf
Checking username availability now...
Taken on asciinema
Taken on behance
Taken on deviantart
Impossible on facebook
Taken on gitlab
Taken on github
Traceback (most recent call last):
  File "cli.py", line 26, in <module>
    main()
  File "cli.py", line 19, in main
    elif res['status'] == 404 or res['status'] == 301:
KeyError: 'status'
```

**Comment by seeeturtle** [comment]
Does it occurs also for username_api.py?
And what website are having problem with?

2018. 9. 23. 오후 9:08 Brendan Coles <notifications@github.com> 작성:

**Comment by bcoles** [comment]
@seeeturtle Presumably an issue with the `instagram` check. I haven't tried with `username_api.py`
